//
// Created by titan on 29.11.2021.
//

#ifndef INTERFACES_INHERITANCE_FABRIC_METHOD_FACTORY_H
#define INTERFACES_INHERITANCE_FABRIC_METHOD_FACTORY_H


class factory {

};


#endif //INTERFACES_INHERITANCE_FABRIC_METHOD_FACTORY_H
