//
// Created by titan on 29.11.2021.
//

#ifndef INTERFACES_INHERITANCE_FABRIC_METHOD_GREP_H
#define INTERFACES_INHERITANCE_FABRIC_METHOD_GREP_H


class grep {

};


#endif //INTERFACES_INHERITANCE_FABRIC_METHOD_GREP_H
