//
// Created by titan on 29.11.2021.
//

#ifndef INTERFACES_INHERITANCE_FABRIC_METHOD_PARSER_H
#define INTERFACES_INHERITANCE_FABRIC_METHOD_PARSER_H


class parser {

};


#endif //INTERFACES_INHERITANCE_FABRIC_METHOD_PARSER_H
