//
// Created by titan on 29.11.2021.
//

#ifndef INTERFACES_INHERITANCE_FABRIC_METHOD_READFILE_H
#define INTERFACES_INHERITANCE_FABRIC_METHOD_READFILE_H


class readfile {

};


#endif //INTERFACES_INHERITANCE_FABRIC_METHOD_READFILE_H
