//
// Created by titan on 29.11.2021.
//

#ifndef INTERFACES_INHERITANCE_FABRIC_METHOD_REPLACE_H
#define INTERFACES_INHERITANCE_FABRIC_METHOD_REPLACE_H


class replace {

};


#endif //INTERFACES_INHERITANCE_FABRIC_METHOD_REPLACE_H
