//
// Created by titan on 29.11.2021.
//

#ifndef INTERFACES_INHERITANCE_FABRIC_METHOD_SORT_H
#define INTERFACES_INHERITANCE_FABRIC_METHOD_SORT_H


class sort {

};


#endif //INTERFACES_INHERITANCE_FABRIC_METHOD_SORT_H
