//
// Created by titan on 29.11.2021.
//

#ifndef INTERFACES_INHERITANCE_FABRIC_METHOD_WORKER_H
#define INTERFACES_INHERITANCE_FABRIC_METHOD_WORKER_H


class worker {

};


#endif //INTERFACES_INHERITANCE_FABRIC_METHOD_WORKER_H
