//
// Created by titan on 29.11.2021.
//

#ifndef INTERFACES_INHERITANCE_FABRIC_METHOD_WRITEFILE_H
#define INTERFACES_INHERITANCE_FABRIC_METHOD_WRITEFILE_H


class writefile {

};


#endif //INTERFACES_INHERITANCE_FABRIC_METHOD_WRITEFILE_H
